### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by mcPear** [kingoflolz/mesh-transformer-jax#10]
Hi, would it be possible to run GPT-J on GPU in the future?

**Comment by j-frei** [comment]
Correct me if I'm wrong but I think the script `resharding_example.py` acts as a demo for that particular use case.  
However I still have trouble getting it running properly...

**Comment by mcPear** [comment]
@j-frei Yes, it is, thanks! I haven't read readme carefully enough.

**Comment by j-frei** [comment]
It's finally working on my setup (A100). :)
One should ensure to have the GPU-accelerated jaxlib package installed. If it is not, one can simply install it like this:
```bash
pip install jaxlib==0.1.67+cuda110 -f https://storage.googleapis.com/jax-releases/jax_releases.html
```

**Comment by AeroScripts** [comment]
It's also a good idea to use these environment variables
```
XLA_PYTHON_CLIENT_PREALLOCATE=false XLA_PYTHON_CLIENT_ALLOCATOR=platform
```
if you have limited vram try decreasing "seq" but you'll need at least 19gb

Also if you are on a RTX 3000 series card make sure to get "+cuda111" not "+cuda110"

**Comment by j-frei** [comment]
Yes, it is documented in the header of `resharding_example.py` as well.

The +cudaXYZ depends on the cuda/driver version you have installed/available on your system.
(e.g. what CUDA version `nvidia-smi` will tell you + installed CUDA toolkit/`nvcc --version` you may use...)
I just use the most latest Docker/PyTorch image that matches the CUDA version of my Nvidia host driver to avoid unnecessary hassle.

**Comment by kingoflolz** [comment]
Looks like y'all figured it out, if you have suggestions on what should be added to the documentation, I'll happily accept a PR to add a new markdown file for getting started on GPU

**Comment by heisen273** [comment]
@kingoflolz , @AeroScripts , since you've tested it - perhaps you can let me know what was the model performance during your tests on GTX3090(i.e. what was the time_taken for example function `infer("EleutherAI is")`)?
 I'm considering whether it's a good idea to purchase this videocard and use it with GPT-j model. 
 
Thank you for letting me know
