### ISSUE TITLE
Selfhosted GPT-J

### ISSUE THREAD

**Issue by vojmar** [kingoflolz/mesh-transformer-jax#102]
Since i am new to this field i am not sure i understand the requirements for running selfhosted version properly. When i try to run queries on https://6b.eleuther.ai/ they tend to fail with errors like: "Unable to connect to the model. Please try again.". If i wanted to run my own instance what kind of hardware do i need?
And is is there an option to rent something capable of running that? Like a VPS?

**Comment by kingoflolz** [comment]
the API can be hosted on a TPU (see device_serve.py), and can also be hosted on a GPU (see https://github.com/paulcjh/gpt-j-6b/blob/main/gpt-j-t4.ipynb)
