### ISSUE TITLE
Colab GPT-J-6B Inference Demo.ipynb error

### ISSUE THREAD

**Issue by panweigood** [kingoflolz/mesh-transformer-jax#103]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-a61c7aa5df54> in <module>()
     28 maps.thread_resources.env = maps.ResourceEnv(maps.Mesh(devices, ('dp', 'mp')))
     29 
---> 30 tokenizer = transformers.GPT2TokenizerFast.from_pretrained('gpt2')

29 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/__init__.py in <module>()
    144 
    145 # Normalization layers.
--> 146 from tensorflow.python.keras.layers.normalization import LayerNormalization
    147 from tensorflow.python.keras.layers.normalization_v2 import SyncBatchNormalization
    148 

ImportError: cannot import name 'LayerNormalization' from 'tensorflow.python.keras.layers.normalization' (/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/normalization/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by yoni12345678** [comment]
I Have this issue too, I know the line 146:
`from tensorflow.python.keras.layers.normalization import LayerNormalization` 
 Should be replaced with :
`from tensorflow.python.keras.layers import LayerNormalization` 
Its probably because of tensorflows latest version 2.6

**Comment by 0gray1** [comment]
Downgrading tensorflow using `!pip install tensorflow==2.5.0` fixed the issue for me

**Comment by siscia** [comment]
@0gray1 can you post your notebook?

I am afraid the fix is dependent on the state on the python runtime (which libs have already been loaded) and also the execution order of the commands.

**Comment by kingoflolz** [comment]
If someone has a fix that works, I would greatly appreciate a pull request (please test the fix after factory resetting the runtime)

**Comment by yoni12345678** [comment]
You can downgrade tensorflow to version 2.5
Just add `!pip install tensorflow==2.5` in the first line, it works for me

**Comment by siscia** [comment]
The suggested fix, seems to bring some dependencies incompatibilities.

Do we have any frozen dependencies somewhere? Maybe a docker image?

@yoni12345678 , it doesn't seems to work your suggestion. Did you run a fa tory reset on the colab?

**Comment by yoni12345678** [comment]
@siscia I restarted and ran all, it worked

**Comment by yoni12345678** [comment]
The optimal solution is to change :
from tensorflow.python.keras.layers.normalization import LayerNormalization

to: `from tensorflow.python.keras.layers import LayerNormalization`

but I dont know where this code is taken from and who can change it

**Comment by kingoflolz** [comment]
fixed in 4c61cfa
