### ISSUE TITLE
Expected time to inference on a 3090 RTX

### ISSUE THREAD

**Issue by adventdtr** [kingoflolz/mesh-transformer-jax#104]
Hi,

What is the expected time to inference the slim GPT-J model a node with a 3090 RTX with 128 GB of ram?
I am seeing 40-50 seconds at the moment. Is there any advice on how to speed it up or is this what we should expect from this hardware?

**Comment by kingoflolz** [comment]
You can try the huggingface implementation in pytorch, I believe that has faster inference times on GPU. (https://github.com/huggingface/transformers/pull/13022)

**Comment by bryanmcguire** [comment]
huggingface/transformers#13022 has to be loaded with .half() for inference on RTX3090 as it's slightly too big to fit in 24G
I'm bummed that I need v100 or better to work with it

**Comment by StellaAthena** [comment]
The [EleutherAI/gpt-j-6B](https://huggingface.co/EleutherAI/gpt-j-6B) checkpoint is only 11 GB. Why can't you fit it in 24 GB GPU?

**Comment by bryanmcguire** [comment]
@StellaAthena 
I'm using 
model = AutoModelForCausalLM.from_pretrained("EleutherAI/gpt-j-6B").half().to('cuda:0')
and that might be the problem.  I haven't tried with GPTJForCausalLM

**Comment by kingoflolz** [comment]
@bryanmcguire @StellaAthena Please move support for the huggingface implementation to their repo
