### ISSUE TITLE
Can I use this script to convert my data to tfrecords?

### ISSUE THREAD

**Issue by Aryagm** [kingoflolz/mesh-transformer-jax#117]
I have a folder full of python files on which I want to fine-tune GPT-J. If I use this script given in the GPT-neo repository, will I be able to convert them into a tfrecords format compatible with GPT-J? 

Or will I need to modify it in order for it to suit GPT-J?

Here is the link to the script: https://github.com/EleutherAI/gpt-neo/blob/master/data/create_tfrecords.py

Thanks,

**Comment by kingoflolz** [comment]
You can use this script https://github.com/kingoflolz/mesh-transformer-jax/blob/master/create_finetune_tfrecords.py

**Comment by Aryagm** [comment]
Thank you  :)
