### ISSUE TITLE
[Colab] Your session crashed after using all available RAM

### ISSUE THREAD

**Issue by 1234igor** [kingoflolz/mesh-transformer-jax#120]
Hi! First of all, thanks for providing Colab Demo. 

However, recently it has stopped working for me, saying "Your session crashed after using all available RAM". 

Any ways to fix this?

**Comment by vfbd** [comment]
Some TPU Colab instances don't have enough system RAM (~13-14 GiB are required) to run the Colab Demo. You can try the "lowmem" branch for now from our fork to see if it works better, just replace the `!git clone https://github.com/kingoflolz/mesh-transformer-jax.git` in the Colab demo notebook with `!git clone -b lowmem https://github.com/VE-FORBRYDERNE/mesh-transformer-jax.git`

**Comment by kingoflolz** [comment]
Thanks for the workaround @vfbd . I would be happy to take a PR for that change too if it helps with colab.
