### ISSUE TITLE
Incompatible checkpoints (1,) vs (1, 4096)

### ISSUE THREAD

**Issue by niyoushanajmaei** [kingoflolz/mesh-transformer-jax#124]
Hello,

I am trying to infer (just to check everything and later fine tune) with the full weights on a CPU. I have set `"cores_per_replica": 1` and following the resharding example I am using `network.state = read_ckpt(network.state, "/home/step_383500/", 8, shards_out=cores_per_replica)` for reading the checkpoints but I get the following error:
 
key shape (1, 2)
in shape (1, 2048)
dp 1
mp 1

assert x.shape == old.shape, f"Incompatible checkpoints {x.shape} vs {old.shape}"
AssertionError: Incompatible checkpoints (1,) vs (1, 4096)

the code:

```
params = {
  "layers": 28,
  "d_model": 4096,
  "n_heads": 16,
  "n_vocab": 50400,
  "norm": "layernorm",
  "pe": "rotary",
  "pe_rotary_dims": 64,
  "early_cast": True,
  "seq": 2048,
  "cores_per_replica": 1, 
  "per_replica_batch": 1,
}

per_replica_batch = params["per_replica_batch"]
cores_per_replica = params["cores_per_replica"]
seq = params["seq"]

params["sampler"] = nucleaus_sample
params["optimizer"] = optax.scale(0)

devices = np.array([jax.devices()[0]]).reshape((1, 1))
maps.thread_resources.env = maps.ResourceEnv(maps.Mesh(devices, ('dp', 'mp')))

tokenizer = transformers.GPT2TokenizerFast.from_pretrained('gpt2')

network = CausalTransformer(params)

start = time.time()

network.state = read_ckpt(network.state, "/home/step_383500/", 8, shards_out=cores_per_replica)

network.state = jax.device_put(network.state, jax.devices("cpu")[0])
```

Moreover, when fine-tuning locally with a CPU are there any changes I have to make to device_train other than the arguments of read_ckpt(as in the resharding example?) and changing directory paths?

**Comment by kingoflolz** [comment]
You need to either load the slim checkpoints or the remove this line
`params["optimizer"] = optax.scale(0)`
