### ISSUE TITLE
Difference between the inputs to GPT-J6B and GPT-2?

### ISSUE THREAD

**Issue by BakingBrains** [kingoflolz/mesh-transformer-jax#127]
Can you please give some information regarding what is the difference between feeding the data to GPT-J and GPT-2, let's say for example python code generation. Is the data feeding method is same for both models? Because, in GPT-2 to generate python code we need to give a piece of python code where as in GPT-J6B we can only give the prompts like 'write a program to add two numbers'

**Comment by kingoflolz** [comment]
There is significant differences in the data distribution between the two models, and this means prompts don't necessarily transfer.
