### ISSUE TITLE
Improvement in accuracy

### ISSUE THREAD

**Issue by paramjeet2021** [kingoflolz/mesh-transformer-jax#133]
I have trained this model on my custom data which is about 80MB. After training a model, when I try to predict then I realise that it is not generating appropriate content as it is not replying to a question correctly. For example 
Input:
Is more downforce in a car always better?
Output:
\\u001b[0m 2.0-1 and 0.3 m2 are normalized with the Anemmer so that theers are not all possible. When the calculations are performed with the C. The speed of the flow separation branch is out the amount of the vertical axis and the vertical axis of the, as shown in the vertical plane (Fig 10) they are deliberately to the control system (P is out). The flight-mill shown in Fig 2. For the vertical shaft and fixed/seesaw ( investigated) obtained from theaging torque) in the vertical plane. The shape in the fixed condition was significantly larger when the beetles were level (BL) given the yaw design showed that the lift produced was the external wing during prolonged flight (Fig 11). While banking seems to reduce flapping asymmetrically similar flight at the two most of each flight-mill, 7 beetles were level (RMANOVA, F1,9 = 0.094, p = 0.1, Fig 1.2, respectively). In contrast, the beetles in the flight-mill rotating at the same speed of the beetles, but actuallyes 2. In contrast, the insect experiences an important plots that is lift forces. Since the interaction between the flapping

2.)   Input:  What is an angle of attack in aerodynamics?
Output:
\\u001b[0m Thus, as a way to reduce flapping kinematics did not have lower flapping amplitude,\\n(11)\\n,\\n(11)\\nwhere l is the deflected angle with the larger normal Seaver and wing side. in the vertical plane (Fig 3A). The change in position of the point of attachment to the tether with wing side (Fig 3A). The aerodynamic force needed to keep the instantaneous flight-mill rotating at the constant flight speed and weight of the flight-mill, with the circular trajectory is forced by the wing length. The body mass moment of the flight-mill is the wingbeat kinematics of the three high-speed video frames. The U-2D positions of the body axes, the square of the flight-mill, and the angular deceleration of the flight-mill, and the\\n(2)\\nwhere Izz is the mass of the measured flight-mill in the fixed condition, mass m3 at the constant speed. This force did not differ between the flight-mill speed was much lower than 100% of the body weight in the air resistance to rotation. The flight-mill speed of the beetle is particularly true here, lift to fly in the vertical plane

I have also used question along with 2-3 lines of content still results are not good. I also used the GPT-3 API on the same content and quality is much better with GPT3. 

Any suggestion to improve the model, Should I play around with the architecture or parameters or do you suggest something other way out?

**Comment by kingoflolz** [comment]
I'm not able to provide support for downstream applications, but I suggest looking into the fine tuning data
