### ISSUE TITLE
create_finetune_tfrecords.py getting killed prematurely.

### ISSUE THREAD

**Issue by Aryagm** [kingoflolz/mesh-transformer-jax#136]
I have a dataset of about 13Gb. It is a folder of text files. When I run the `create_finetune_tfrecords.py` script using `python3 generate_tfrecord.py data finaldata_1349320.tfrecords --normalize-with-ftfy --seed 42`, the process gets terminated early as so:

```
2021-10-02 22:33:27.094704: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-10-02 22:33:27.094737: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
27%|██████████████▏                                     | 311988/1148393 [1:10:23<3:03:22, 76.02it/s]
Killed
```

Is there a way to solve this issue? I am running it on a VM with about 32 gigs of RAM.

Thanks,

**Comment by kingoflolz** [comment]
Looks like you are running out of memory. You can try the original script which this is based on https://github.com/EleutherAI/gpt-neo/blob/master/data/create_tfrecords.py , which lacks some features but should require less memory.

**Comment by Aryagm** [comment]
> 
> 
> Looks like you are running out of memory. You can try the original script which this is based on https://github.com/EleutherAI/gpt-neo/blob/master/data/create_tfrecords.py , which lacks some features but should require less memory.

Will this script cause a decrease in performance compared to the script in this repository?
