### ISSUE TITLE
problem in downloading the slim weights

### ISSUE THREAD

**Issue by whoislimshady** [kingoflolz/mesh-transformer-jax#139]
i was downloading the slim weights but it dosen't work and giving me the error saying
`"connection timeout error"`
![Screenshot from 2021-10-15 15-52-21](https://user-images.githubusercontent.com/72891217/137473246-df3fa995-ef8d-4786-853f-c3cf49859e98.png)

so to be sure i tried to run this on both colab and personal getting the same error is there any solution to this problem

**Comment by mirandali707** [comment]
I've been having this issue too!

**Comment by world177** [comment]
There are some mirrors others are currently hosting, but nothing official. 

* http://batbot.tv/ai/models/GPT-J-6B/
* http://eaidata.bmk.sh/data/GPT-J-6B/
* https://archive.org/details/GPT-J-6B-weights

The host "the-eye.eu" should be back online soon.

**Comment by whoislimshady** [comment]
yes thanks
