### ISSUE TITLE
resharding_example.py errors with jax==0.2.13

### ISSUE THREAD

**Issue by aaronrmm** [kingoflolz/mesh-transformer-jax#14]
Running resharding example gave the following error. Installing jax==0.2.12 fixed the issue.

```TypeError: One of xmap results has an out_axes specification of ['batch', ...], but is actually mapped along more axes defined by this xmap call: shard```

Environment:
python 3.8.5
ubuntu 20.04
a single rtx3090

all python lib versions exactly as in requirements.txt except
flask==1.1.4
ftfy==6.0.3
func-timeout==4.3.5
smart-open==5.1.0

**Comment by kingoflolz** [comment]
You must use jax==0.2.12
