### ISSUE TITLE
checkpoint saving args broken/unused

### ISSUE THREAD

**Issue by ablacklama** [kingoflolz/mesh-transformer-jax#141]
The checkpoint saving in [device_train.py](device_train.py) has several options that are either broken or very confusing. I'll go through them on by one. Mostly i'm wondering what you felt like they should do, I'm willing to do the coding. I also think we should document the config file option somewhere. And any changes applied to `device_train.py` should probably be mirrored in `train.py`.

## keep_n: from `save()`

My intuition is that this should be the max number of checkpoints to keep while training. So if it has a value of `3`, after the fourth checkpoint is saved, the first is deleted, and so on. But right now it looks like it has a weird interaction with `delete_old` where if `delete_old` is `False` it will only delete the `aux` state. That's a bit weird since there's really no reason to delete the aux state if you're not deleting the checkpoint. 

Additionally, it's hard coded  at `3`. So setting `keep_every` in the config won't allow you to keep more than 3.

## keep_every: from `config.json`

It's just not used in the saving code.

As for what it *should* do. I think it should exempt certain checkpoints from being deleted. It can either:
 1. count the same way `ckpt_every` does. So `ckpt_every=5` and `keep_every=10` would mean you'd keep every other checkpoint.
 2. Just count the checkpoints that are saved. So `keep_every=2` would save every other checkpoint no matter what `ckpt_every` was set to.
 
 The second one sounds more intuitive to me.
 
 ## delete_old: from `save()`

 Except for the weird interaction with `keep_n` mentioned above, it's fine.
 
 The problem is that it's hard set to `True`, and i think it's not really needed. If `keep_every` and `keep_n` are working, I don't see the need for it to exist.
 
 
 # Examples

Here's a few examples of what someone might want to do with these params and how they would work.
For the sake of the examples, i'm going to be using the second version of what I think `keep_every` should do. But these would all work with version 1 as well if you changed the values a bit.
 
## Don't have a lot of space, but want to retain some backups spread out over the training.

```python
keep_n=3
keep_every=10
ckpt_every=5
```

The latest checkpoint will always be on disk, as well as up to 3 other checkpoints. Those other 3 will be spaced out backwards in training every `10 x ckpt_every`. 

So with you could have checkpoints on disk of [100, 150, 200, 205]

## Just keep the latest
```python
keep_n=0
keep_every=Any
ckpt_every=Any
```

## Keep every 10 no matter how many
```python
keep_n=-1
keep_every=10
ckpt_every=Any
```

**Comment by kingoflolz** [comment]
Thanks for writing this detailed description!

The overall intention is to have 2 sets of checkpoints, one set which is deleted frequently and is just used to resume in case of anything happening to training (e.g. preemption). This is the intention of the keep_n parameter. The other set is for checkpoints to be stored permanently, in case of any more subtle errors which cannot be automatically recovered from, and will never be deleted (e.g. if the model diverges and nobody is around to notice, don't want to delete all the checkpoints).

Hope that makes the intention clear, happy to accept PRs which help document/clarify/fix the implementation.
