### ISSUE TITLE
need guide with docker, not an issue

### ISSUE THREAD

**Issue by noman00910** [kingoflolz/mesh-transformer-jax#142]
Can anybody guide me how to completely setup text generation with docker. I am facing a lot of issues running on ubuntu. Also want to know how to add Full weights (including optimizer params, 61GB) in the script.

**Comment by jleacox** [comment]
> Can anybody guide me how to completely setup text generation with docker. I am facing a lot of issues running on ubuntu. Also want to know how to add Full weights (including optimizer params, 61GB) in the script.

Hopefully we get an answer on my similar issue - I've been trying to set it up for a couple of days at this point and yes it's quite confusing. Maybe we can catch up and exchange learnings so far.

**Comment by jleacox** [comment]
> Can anybody guide me how to completely setup text generation with docker. I am facing a lot of issues running on ubuntu. Also want to know how to add Full weights (including optimizer params, 61GB) in the script.

Checkout my (now closed issue)! :)

**Comment by kingoflolz** [comment]
There is no advantage to using the full weights for inference. The docker setup is not designed to run locally, so I would suggest you install the package directly.

**Comment by jleacox** [comment]
> There is no advantage to using the full weights for inference. The docker setup is not designed to run locally, so I would suggest you install the package directly.

How do you mean "no advantage" out of curiousity?
