### ISSUE TITLE
unable to extract step_383500.tar.zstd.

### ISSUE THREAD

**Issue by davzeng** [kingoflolz/mesh-transformer-jax#143]
I'm unable to extract step_383500.tar.zstd.

I have a pretty simple issue.

The type of this file is ZSTD and it doesn't seem to be supported by any archive. I tried searching up the file type and got nothing(everything I got was related to .zst and a tool called Zstandard, which is also called zstd). How am I suppose to decompress this file.

**Comment by srinikethanr** [comment]
apt install zstd
tar -I zstd -xvf step_383500.tar.zstd

**Comment by VishalSharmavj** [comment]
Also, for windows, there is an extractor named PeaZip.

**Comment by kingoflolz** [comment]
The format is zstandard, see this for a few different implementations: https://en.wikipedia.org/wiki/Zstandard#Usage
