### ISSUE TITLE
Colab demo does not work

### ISSUE THREAD

**Issue by JialuZhang** [kingoflolz/mesh-transformer-jax#145]
ERROR: Cannot install -r mesh-transformer-jax/requirements.txt (line 14) and -r mesh-transformer-jax/requirements.txt (line 9) because these package versions have conflicting dependencies.

The conflict is caused by:
    lm-eval 0.0.1 depends on tensorflow-estimator==2.6.0
    tensorflow-cpu 2.5.2 depends on tensorflow-estimator<2.6.0 and >=2.5.0
    lm-eval 0.0.1 depends on tensorflow-estimator==2.6.0
    tensorflow-cpu 2.5.1 depends on tensorflow-estimator<2.6.0 and >=2.5.0
    lm-eval 0.0.1 depends on tensorflow-estimator==2.6.0
    tensorflow-cpu 2.5.0 depends on tensorflow-estimator<2.6.0 and >=2.5.0rc0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
Processing ./mesh-transformer-jax

**Comment by JialuZhang** [comment]
I got the previous error when I tried to use the colab demo. 

The demo worked last week but this problem surface.

I tried to change    ```!pip install mesh-transformer-jax/ jax==0.2.12 tensorflow==2.5.0'''
to ```!pip install mesh-transformer-jax/ jax tensorflow''' but it still did not work.

**Comment by kremlin-** [comment]
#144

**Comment by kingoflolz** [comment]
dupe
