### ISSUE TITLE
Formatting and Problems while creating tfrecords file for fine tuning gpt. 0 byte tfrecords getting created.

### ISSUE THREAD

**Issue by VishalSharmavj** [kingoflolz/mesh-transformer-jax#147]
I'm trying to fine-tune the 6b parameter model by first creating tfrecords through "create_finetune_tfrecords.py"

The input file I'm giving is having text as,

<|endoftext|>causes and condition of sinusitis:Acute sinusitis can be triggered by a cold or allergies and may resolve on its own. Chronic sinusitis lasts up to eight weeks and may be caused by an infection or growth. Symptoms include headache, facial pain, runny nose and nasal congestion.<|endoftext|>

It runs and shows,

```
Creating TFRecords from files: ['C:\\Users\\vishal\\Desktop\\Code\\GPT\\sample_train.txt']                                             
reading/tokenizing files: 100%|███████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 333.28it/s] 
dropped 63 tokens of trailing data
```

But the tfrecords file created is of 0 bytes. Is there something wrong with the formatting of the input txt file as I need a compatible lm format for question and answer or heading and summary of medical notes.

Note: I think that creating tfrecords with the given .py file does the conversion with help of transformers and gpt-2 tokenizer which I'm running on a local Windows PC. Else, I have done the rest of setup like TPU VM etc as per the guide.

**Comment by vfbd** [comment]
Pretty sure that's not enough training data. The minimum required amount of training data (in tokens) is something like 2049 times the `gradient_accumulation_steps` in the config JSON file for your fine-tune.

**Comment by VishalSharmavj** [comment]
> Pretty sure that's not enough training data. The minimum required amount of training data (in tokens) is something like 2049 times the `gradient_accumulation_steps` in the config JSON file for your fine-tune.

I'm able to generate tfrecords by changing the 'sequence_length' parameter to 16 in 'arrays_to_sequences' function. Will it contradict with something else? Also, anybody having any idea about how to format the input txt file for question and answer or heading and summary. Can it be like as I already made in form of key value separated by endoftext.

**Comment by kingoflolz** [comment]
The current scripts are designed for megabytes worth of data, and ideally you want at least hundreds of megabytes for good results. You can look into existing literature about data formatting, see appendix G in the GPT3 paper.
