### ISSUE TITLE
Regarding Fine-tuning.

### ISSUE THREAD

**Issue by BakingBrains** [kingoflolz/mesh-transformer-jax#148]
I have refered this [https://github.com/kingoflolz/mesh-transformer-jax/blob/master/howto_finetune.md](https://github.com/kingoflolz/mesh-transformer-jax/blob/master/howto_finetune.md) for finetuning process. 

Here, we use google buckets to store data and model, but I have very small amount of data. Can I remove the bucket dependency and run the process with small data using TPU? (stroing the model and the data in google drive)

**Comment by kingoflolz** [comment]
Its possible, although I suspect you would have to dig in to of the code and procedure to make it work properly. If you decide to try this, I'll be happy to accept a pull request for updates to code/documentation

**Comment by BakingBrains** [comment]
Sure, I would love to try.

Thanks
