### ISSUE TITLE
limitation min_length=1024

### ISSUE THREAD

**Issue by LokiInside** [kingoflolz/mesh-transformer-jax#155]
how to apply this fix https://github.com/microsoft/DeepSpeed/pull/1114/commits/5e9b420e543e83d6fa1c64f86f9c44a708f37125
it is imported this issue, because ai starts to explain complex topic problems and then it stops 
at GitHub I was find some [issues](https://github.com/microsoft/DeepSpeed/issues/1112) at this topic
https://github.com/microsoft/DeepSpeed/issues/1112#issuecomment-856942487
![Bildschirmfoto 2021-11-18 um 20 27 24](https://user-images.githubusercontent.com/75278757/142484061-ea628d60-4c8a-4a44-9134-8edce3056aac.png)

**Comment by kingoflolz** [comment]
I cannot support other implementations of GPT-J, please file an issue in repository which you are using.
