### ISSUE TITLE
Finetuning and training minimum requirements

### ISSUE THREAD

**Issue by AnassKartit** [kingoflolz/mesh-transformer-jax#156]
Hello,
What is the minimum requirements for finetunning and inference? is TPU mandatory? what are the costs/time needed to train a small dataset used in the finetuning article?

**Comment by kingoflolz** [comment]
This codebase is designed for inference and finetuning on TPU. The cost of TPU instances are available from google, and fine tuning runs at around 5000 tokens per second on a TPU v3-8
