### ISSUE TITLE
Execute the model in a local machine (or WSL)

### ISSUE THREAD

**Issue by Dr-NULL** [kingoflolz/mesh-transformer-jax#159]
Hi, I want to execute this model in my local pc, to make some tests, using nodejs (or python). My question is how can I use this model with nodejs or python locally in my computer?

I develop my applications in WSL (with Ubuntu), so I can make projects in an linux environment.

Regards.

**Comment by kingoflolz** [comment]
I suggest you use the huggingface implementation of GPT-J (see https://huggingface.co/docs/transformers/master/model_doc/gptj)
