### ISSUE TITLE
sample data configuration for finetuning

### ISSUE THREAD

**Issue by AnassKartit** [kingoflolz/mesh-transformer-jax#160]
can you provide a sample data for fine tunning and what command line parameters are required, I tried calculating the training epochs based on sequence but did not work my sample data has 
can I do this sample:
for this txt file:
Classify the following message into one of the following categories: Billing, Bug, Feature request, Urgent 

Message: I was charged incorrectly for last month. It charged me $100, but should have been $80 due to removing one of our developers off your platform before the billing cycle started. Please refund my account.

Category: Billing

<|endoftext|>

Classify the following message into one of the following categories: Billing, Bug, Feature request, Urgent 

Message: Hi, my email templates are not loading properly. I've tried selecting multiple of them but the email is not populating correctly.

Category: Bug

<|endoftext|>

command line for tunning:
do I need this parameters --treat-eot-as-text for finetuning?
 python3 ./create_finetune_tfrecords.py  --input_path train --name customercomplaints --treat-eot-as-text

what configs?
configs:
{
  "layers": 28,
  "d_model": 4096,
  "n_heads": 16,
  "n_vocab": 50400,
  "norm": "layernorm",
  "pe": "rotary",
  "pe_rotary_dims": 64,

  "seq": 2048,
  "cores_per_replica": 8,
  "per_replica_batch": 1,
  "gradient_accumulation_steps": 16,

  "warmup_steps": 7,
  "anneal_steps": 65,
  "lr": 5e-5,
  "end_lr": 1e-5,
  "weight_decay": 0.1,
  "total_steps": 72,

  "tpu_size": 8,

  "bucket": "customer",
  "model_dir": "mesh_jax_quote_6B_rotary",

  "train_set": "customer.train.index",
  "val_set": {},

  "eval_harness_tasks": [
    "lambada",
    "piqa",
    "hellaswag",
    "winogrande",
    "mathqa",
    "pubmedqa"
  ],

  "val_batches": 100,
  "val_every": 500,
  "ckpt_every": 500,
  "keep_every": 10000,

  "name": "quotes",
  "wandb_project": "mesh-transformer-jax",
  "comment": ""
}

**Comment by kingoflolz** [comment]
I'm not able to provide any sample data or advice for configs, please see the documentation in create_finetune_tfrecords.py
