### ISSUE TITLE
end sequence possible?

### ISSUE THREAD

**Issue by sharaku17** [kingoflolz/mesh-transformer-jax#169]
Hi, 

I just want to ask if there is a possibility in the colab demo to define a end_sequence parameter, like `end_sequence = '###'` for example and the model will just generate text until this sequence and not further ? 

thank you!

**Comment by kingoflolz** [comment]
I suggest you use the huggingface implementation (https://huggingface.co/EleutherAI/gpt-j-6B) for more advanced sampling parameters. There is no ability to stop the generation on a particular sequence in this repository.
