### ISSUE TITLE
the-eye.eu down - alternative access to GPT-J-6B/step_383500_slim.tar.zstd ?

### ISSUE THREAD

**Issue by PhilWicke** [kingoflolz/mesh-transformer-jax#170]
Thank you for your hard work and dedication to the project. 
I've been trying to load the slim checkpoint from the-eye.eu. Apparently, the side is down. I've checked any sort of access, but it probably is an outage on their end ([https://downforeveryoneorjustme.com/the-eye.eu](https://downforeveryoneorjustme.com/the-eye.eu)).

They might resolve it shortly - or maybe not. Is there any alternative address to wget GPT-J-6B/step_383500_slim.tar.zstd ?
Thank you.

**Comment by bolinocroustibat** [comment]
Same issue here, if there's an alternate hosting that would be great!

**Comment by bolinocroustibat** [comment]
FYI, the-eye.eu is down for maintenance only for a few days from 2021 Dec. 11th to 2021 Dec. 13th.
Source: https://twitter.com/arankomatsuzaki/status/1470244542670589952
Thanks to @AranKomat for quick explanation!

**Comment by PhilWicke** [comment]
It's still unavailable. Maybe I'm just impatient and it's a different time-zone etc.

**Comment by mosmos6** [comment]
Still down. I should have downloaded it locally.

**Comment by AranKomat** [comment]
Apparently, the-eye was affected by the tornado, and they're currently working on getting it back up. 

You can still load the model from HF though. Anyway, please take a look at the discussion in gpt-j channel at EleutherAI. If you have any question, they can answer your question :)

**Comment by PhilWicke** [comment]
Thanks. The HF model is not the "slim" model though, right? (https://huggingface.co/EleutherAI/gpt-j-6B)
If I'm trying to load the HF model, it'll exceed the memory in the Colab file. Maybe the slim model can be added to HF?

**Comment by dicer2000** [comment]
Any chance we could get you to load the slim model in an alternative server?  We'd really like to try it out.  Thanks

**Comment by mosmos6** [comment]
I used this page.
https://www.kaggle.com/curtisasmith/gptj6b-slim-weights-for-inference/version/1
I don’t know this kaggle user but I’d like to say thank you.

**Comment by dicer2000** [comment]
> https://www.kaggle.com/curtisasmith/gptj6b-slim-weights-for-inference/version/1

That worked great, @mosmos6.  Thanks!

**Comment by jmherrera11** [comment]
I found this one. No idea who runs this site but models are stored there

http://eaidata.bmk.sh/data/GPT-J-6B/

**Comment by mosmos6** [comment]
wow it has meta data too. @ jmherrera11

**Comment by bolinocroustibat** [comment]
Thanks @mosmos6 !

**Comment by kingoflolz** [comment]
#182

**Comment by victorbjorklund** [comment]
Another mirror seems to be https://mystic.the-eye.eu/public/AI/GPT-J-6B/step_383500_slim.tar.zstd
