### ISSUE TITLE
Weight download problem

### ISSUE THREAD

**Issue by paramjeet2021** [kingoflolz/mesh-transformer-jax#176]
Hi, I am trying to download weights using the command 
!time wget -c https://the-eye.eu/public/AI/GPT-J-6B/step_383500_slim.tar.zstd

But it keep on trying and does not connect. It seems this link is down and would you let me know when it would be up and possible to download the weights.

**Comment by paramjeet2021** [comment]
Any idea, When can I download these weights. I need these weights to execute my script or is there any way to download these weights from some other source?

**Comment by shimoshida** [comment]
@paramjeet2021 If you want FP16 model, the following mirror server exists;
https://archive.org/details/GPT-J-6B-weights

**Comment by paramjeet2021** [comment]
I have to fine tune the model with my custom data so would like to have full weights. Is it possible to find full weights , not just the bf16 slim weights?

**Comment by shimoshida** [comment]
@paramjeet2021  How about this?
https://mystic.the-eye.eu/public/AI/GPT-J-6B/

**Comment by kingoflolz** [comment]
Fixed by #182
