### ISSUE TITLE
how to speed up the inference time

### ISSUE THREAD

**Issue by whoislimshady** [kingoflolz/mesh-transformer-jax#196]
i am trying to deploy the gpt jax on gcp tpu v2-8 the generation takes around 35 sec which is way to slow i found few blogs which states that with 2-8 we can achieve latency of 5 sec can someone suggest me how to speed up the process and yes i am using the slim weights

**Comment by safeeazeem** [comment]
The first generation always takes time, and then after that its quicker. See table below where I tested the time it takes to generate tokens of different length. This was tested on a v2-8 TPU instance with slim weights.


<html><body>
<google-sheets-html-origin>

Tokens | First Gen | Second Gen | Third Gen
-- | -- | -- | --
100 | 68s | 2.228s | 2.229s
150 | 38.78s | 3.3s | 3.3s
300 | 42s | 6.3s | 6.3s
512 | 45.9s | 10.7s | 10.7s
768 | 52.7s | 15.9s | 15.9s
1024 | 57.51s | 21.13s | 21.13s


</body>
</html>

**Comment by whoislimshady** [comment]
thanks @safeeazeem for the information really appreciate the effort
