### ISSUE TITLE
how to implement stop sequence in gpt j

### ISSUE THREAD

**Issue by whoislimshady** [kingoflolz/mesh-transformer-jax#199]
i have fine tuned gpt j model on a dataset but the when i enter the prompt it correctly generate the answer but keep on generating the prompt answer pair is there any way to tell model to stop the genration after certain character

**Comment by safeeazeem** [comment]
You can follow this [repo](https://github.com/vicgalle/gpt-j-api) for stop sequence. I was able to do it using this repo on a V2-8 TPU. You might have to spin up a new instance for this and make minor changes.

**Comment by whoislimshady** [comment]
@safeeazeem  thanks brother

**Comment by jingrongchen** [comment]
i have the same problem, how did you fix it?
