### ISSUE TITLE
Include context prompt when generating text in Colab

### ISSUE THREAD

**Issue by minimaxir** [kingoflolz/mesh-transformer-jax#2]
It makes it a bit easier to maintain what the prompt is when sharing screenshots of generated text.

<img width="953" alt="Screen Shot 2021-06-08 at 9 49 19 PM" src="https://user-images.githubusercontent.com/2179708/121295183-74d0d680-c8a3-11eb-9c77-093a214e9600.png">

One line change from 

```py
samples.append(tokenizer.decode(o))
```

to

```py
samples.append(f"\033[1m{context}\033[0m{tokenizer.decode(o)}")
```

**Comment by kingoflolz** [comment]
Looks great! Could you make a PR for this?
