### ISSUE TITLE
Using `no_repeat_ngram_size` like HF

### ISSUE THREAD

**Issue by nikhilanayak** [kingoflolz/mesh-transformer-jax#204]
Is there any way I can use something like the `no_repeat_ngram_size` feature from HuggingFace to generate text like [this](https://huggingface.co/blog/how-to-generate#:~:text=50%2C%20%0A%20%20%20%20num_beams%3D5%2C-,no_repeat_ngram_size)? When I generate my text is very repetitive.

**Comment by nikhilanayak** [comment]
Never mind, I figured out how to convert the model to HF. Is there an HF version with TPU support?

**Comment by kingoflolz** [comment]
Not as far as I know, you will likely have better results asking in the HF github/slack

**Comment by leejason** [comment]
> I figured out how to convert the model to HF

Very interesting. Is it possible to know how you did it? I tried several times but failed.
