### ISSUE TITLE
Instruct GPT fine tuning

### ISSUE THREAD

**Issue by Jbollenbacher** [kingoflolz/mesh-transformer-jax#208]
Hello!  

Recently GPT-3 has been updated to the new InstructGPT version, which was produced by further fine-tuning the original GPT-3 models to make them better at following short instructions for zero-shot tasks such as question answering and classification.  The InstructGPT models perform significantly better than the old models. Even the smaller 1.7B and 6.7B parameter InstructGPT models outperform the original 175B parameter model in some ways. 

Are there any plans to produce an InstructGPT-like update to GPT-J? 

Thanks

**Comment by kingoflolz** [comment]
I have no plans to produce more pretrained/finetuned models using this codebase, but the weights are available for others to fine tune.
