### ISSUE TITLE
GPT-J: perplexity for checkpoints

### ISSUE THREAD

**Issue by danyaljj** [kingoflolz/mesh-transformer-jax#211]
Thanks for sharing the [checkpoints](https://mystic.the-eye.eu/public/AI/GPT-J-6B/previous_checkpoints/)! 
Wondering if there is a plot of perplexity as a function of steps #?

**Comment by kingoflolz** [comment]
Information collected during training (ppl, evals etc) can be seen here: https://wandb.ai/eleutherai/mesh-transformer-jax/reports/6B-Rotary--Vmlldzo2NDQxNzY
