### ISSUE TITLE
web app for the model

### ISSUE THREAD

**Issue by RoguePower** [kingoflolz/mesh-transformer-jax#22]
Hi,

I am trying to develop a webapp for the model as it is very good in writing, I used gradio, as I am a data scientist, but it give an eooro for environment. env to be precise, Please share how you developed that app or guide me I am looking forward to giving a demo soon please help.

**Comment by kingoflolz** [comment]
Hi, unfortunately I'm not able to help with developing downstream applications.

**Comment by RoguePower** [comment]
could you at least guide me with the framework you guys used, It would be really helpful
