### ISSUE TITLE
Multiple GPU Error

### ISSUE THREAD

**Issue by pragnakalpdev7** [kingoflolz/mesh-transformer-jax#23]
Hello @kingoflolz,
I am using 4 - T4 GPUs, and facing the below error:
`Traceback (most recent call last):
  File "gpt_j_inference.py", line 59, in <module>
    network.state = read_ckpt(network.state, "step_383500/", 8, shards_out=cores_per_replica)
  File "/home/pragnakalp/Desktop/GPT-J/env_gptj/lib/python3.8/site-packages/mesh_transformer/checkpoint.py", line 145, in read_ckpt
    assert x.shape == old.shape, f"Incompatible checkpoints {x.shape} vs {old.shape}"
AssertionError: Incompatible checkpoints (1, 4096) vs (4, 4096)`
I have passed `cores_per_replica` as 4.
How can I run the code using 4 GPUs, as single GPU results in Memory Error.

**Comment by kingoflolz** [comment]
Unfortunately setting `cores_per_replica` to a value that isn't either 8 or 1 does not work. There exists a PyTorch/HF transformers port which has been tested on 16GB GPUs which I suggest using for inference unless you have a particular need to use this codebase.

See: https://github.com/huggingface/transformers/pull/12106
See also #10 for some scripts that other people have found to work well on T4s.
