### ISSUE TITLE
RuntimeError: CUDA operation failed: cudaGetErrorString symbol not found.

### ISSUE THREAD

**Issue by RoguePower** [kingoflolz/mesh-transformer-jax#24]
I am running resharding with a P5000 GPU and 30gb ram, but this is the error I get, please guide me thanks

**Comment by madisonmay** [comment]
This sounds like this may be an error with your CUDA installation rather than an error with mesh-transformer-jax.

**Comment by RoguePower** [comment]
could you please guide me how to set it up in local jupyterlab, please

**Comment by kingoflolz** [comment]
I suggest you file an issue in the JAX repository as I'm not able to provide support for environment setup issues
