### ISSUE TITLE
stop_sequence like GPT3

### ISSUE THREAD

**Issue by pragnakalpdev7** [kingoflolz/mesh-transformer-jax#26]
Hello @kingoflolz ,
How to make model stop generating further tokens if stop_sequence is found like we have in GPT-3.

**Comment by paulcjh** [comment]
You can convert the model into the transformers library (see here: https://github.com/paulcjh/gpt-j-6b/blob/main/gpt-j-t4.ipynb) and then use the `repetition_penalty` kwarg in the model's `generate` function (as detailed here: https://huggingface.co/transformers/main_classes/model.html).

**Comment by pragnakalpdev7** [comment]
Thanks @paulcjh, I have tried https://github.com/paulcjh/gpt-j-6b/blob/main/gpt-j-t4.ipynb, but on A100 GPU it's taking about 10 seconds to generate 150 tokens, is there anything by which we can reduce the inference time to 1 to 2 seconds.

**Comment by kingoflolz** [comment]
The JAX implementation does not support stop_sequence, but it looks like a workaround has been found using the huggingface implementation. However, I'm not able to support the huggingface implementation, so please consider filing an issue/writing a comment on the PR for optimizations.

**Comment by jroakes** [comment]
I have really enjoyed using this repo to help gain a better understanding of TPUs and Jax.  I am trying to implement a repetition penalty reusing code by huggingface, but am at the limit of my understanding of how parameters ar passed through mapped functions.

I followed the implementation of sampling here: https://github.com/jroakes/mesh-transformer-jax/blob/master/mesh_transformer/penalties.py

This is called in the transformer_shard.py file by updating the carry variable to "carry" (harumph) the last 2048 tokens of context:

```
                def generate_scan_fn(carry, sampler_input):
                    #next_token, decode_state, sample_key = carry
                    next_token, context, decode_state, sample_key = carry
                    sample_key, new_key = jax.random.split(sample_key)

                    #print('Context:')
                    #print(context)

                    logits, new_state = transformer.generate_once(next_token, decode_state)

                    pen_logits = penalty(context, logits, options)

                    next_token, sample_info = sampler(sample_key, pen_logits, sampler_input, options)

                    print('Next Token:')
                    print(next_token)

                    context = jnp.append(context, next_token)[1:]

                    if self.return_logits:
                        output = (next_token, sample_info, logits)
                    else:
                        output = (next_token, sample_info)
                    #new_carry = (next_token, new_state, new_key)
                    new_carry = (next_token, context, new_state, new_key)
                    return new_carry, output
```

I am getting the following error when sending the pre_penalty value in a manner (`"repetition_penalty": np.ones(total_batch) * pred_rep_penalty`) consistent with how top_p and top_k are sent:

```
jax._src.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: Traced<ShapedArray(uint32[2047])>with<DynamicJaxprTrace(level=1/1)>
The error arose in jnp.unique()
While tracing the function generate_scan_fn at /home/jroak/mesh-transformer-jax/mesh_transformer/transformer_shard.py:199, transformed by scan., this concrete value was not available in Python because it depends on the value of the arguments to generate_scan_fn at /home/jroak/mesh-transformer-jax/mesh_transformer/transformer_shard.py:199, transformed by scan. at flattened positions [1], and the computation of these values is being staged out (that is, delayed rather than executed eagerly).
 (https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError)

```

I am working on this to attempt to learn more than anything but would love to offer the changes via a pull request as this really helps in testing on the TPUs.
