### ISSUE TITLE
Reduce inference time

### ISSUE THREAD

**Issue by pragnakalpdev7** [kingoflolz/mesh-transformer-jax#27]
Hi,
I am using A100 GPU, and its taking 10 seconds to generate 150 tokens. How can we reduce the inference time?

**Comment by kingoflolz** [comment]
I have not tested this extensively on GPUs, but I suspect the HF/torch implementation discussed in #17 will likely work better. If that ends up working better, I suggest taking the performance optimization questions up with the HF folks.

**Comment by chris-aeviator** [comment]
@pragnakalpdev7 thanks for sharing the info on what to expect. Does the model fit into a 40GB A100 or do you have a system with the 80GB cards and dedicate a single card?
