### ISSUE TITLE
Error when running device_sample.py

### ISSUE THREAD

**Issue by kurbster** [kingoflolz/mesh-transformer-jax#34]
I have set up a TPU VM and when I try to run device_sample.py I get the following error when calling network.generate:

`TypeError: One of xmap results has an out_axes specification of ['batch', ...], but is actually mapped along more axes defined by this xmap call: shard`

Currently, I am only doing inference so I am using the slim weights. Therefore, I had to change the line of code that sets up the optimizer to this:

`params['optimizer'] = optax.scale(0)`

This is exactly what the collab notebook does which I can run without any errors. Do I need to use the full weights to run device_sample.py? Thank you any help is appreciated.

**Comment by kingoflolz** [comment]
make sure you have installed all the dependencies that the notebook does, especially jax==0.2.12

**Comment by ym-han** [comment]
might also need jax lib to be 0.1.67 (and not 0.1.68).

**Comment by kurbster** [comment]
I had jax 0.2.13 installed. Installing 0.2.12 worked and I was able to use the TPU VM. To install the requirements I used `pip3 install -r requirements.txt`, but maybe I went rogue and did something I don't remember. Thank you!
