### ISSUE TITLE
Unable to connect to the model

### ISSUE THREAD

**Issue by 89z** [kingoflolz/mesh-transformer-jax#35]
Unable to connect to the model. Please try again

I get the above message on this site

https://6b.eleuther.ai/

**Comment by imvetri** [comment]
I was working a while back. May be too much traffic

**Comment by kingoflolz** [comment]
Yeah, just high load

**Comment by Shellfishgene** [comment]
I've tried every now an then for the last 2 days, doesn't seem to work at all anymore?

**Comment by bengoldstein19** [comment]
Has this site been disabled for good?
