### ISSUE TITLE
Web Demo Source Code

### ISSUE THREAD

**Issue by CONIGUERO** [kingoflolz/mesh-transformer-jax#37]
Could the source code for the web demo be pushed into this or other repo? Thanks in advance.

**Comment by kingoflolz** [comment]
The backend is at https://github.com/kingoflolz/mesh-transformer-jax/blob/master/device_serve.py and the frontend is at https://github.com/EleutherAI/text-generation-testing-ui

**Comment by ratthachat** [comment]
@kingoflolz may I know the server spec ( ie. spec of GPU / TPU , and Machine's RAM ) of the web demo ?
