### ISSUE TITLE
device_train.py Error: "AssertionError: Incompatible checkpoints"

### ISSUE THREAD

**Issue by eran-pinhas** [kingoflolz/mesh-transformer-jax#40]
Hey 👋 first of all big thanks for the model and the repo! You've done a brilliant job here, and the model generates some AMAZING results to its size

An having an issue when trying to finetune the 6B model on Google Colab. I roughly followed the modification `device_train.py -h` said  but I'm getting this error: `AssertionError: Incompatible checkpoints (1, 4096) vs (1,)` 

**Reqproduction**

I ran the command with `--tune-model-path` pointing to the downloaded model and the modified `configs/6B_roto_256.json` file with the following changes - train&val sets is poiting to my dataset, changed the number of steps, changed `tpu_size` from 256 to 8 and **changed `cores_per_replica` from 8 to 1**. I suspect the `cores_per_replica` change made a difference in the `mesh_shape` which in turn effects the `shards_in` parameter in `read_ckpt`.

When I printed the `in_shards` thats getting to the `read_ckpt` function it said 1 although I see in the model files that it has 8 `shard_X` folders

Thanks

**Comment by kingoflolz** [comment]
You must use cores per replica as 8, and you also would not be able to tune the model in colab as the tpus do not have enough memory.

**Comment by eran-pinhas** [comment]
Thanks @kingoflolz!
