### ISSUE TITLE
Return probabilities from CausalTransformer.generate()

### ISSUE THREAD

**Issue by narphorium** [kingoflolz/mesh-transformer-jax#41]
The GPT-3 API allows you to fetch probabilities when you generate text. This is helpful for debugging or when using the probabilities to do few-shot classification. It would be great if this feature was also available for GPT-J.

For each generated token there would also be a full list of probabilities for each item in the vocabulary. Then you could look up the probability at any step given a token.

![gpt-3_probabilities_1500x1124](https://user-images.githubusercontent.com/187935/124555509-03c20780-ddec-11eb-8abe-89105f63fe18.jpeg)

**Comment by kingoflolz** [comment]
I would happily accept a PR with this feature, but I have no plans on adding this myself in the foreseeable future. Please reopen if you/anyone else is interested in implementing it and would like to discuss implementation details etc
