### ISSUE TITLE
JAX or Ray Library issue

### ISSUE THREAD

**Issue by paramjeet2021** [kingoflolz/mesh-transformer-jax#43]
I am using this repo to train on a small custom dataset and Jax - 0.2.16  to train this model. However requirements.txt says jax 0.2.12. I really don't know how ray and jax have been working internally but my assumptions is thos code shoud work fine on v3-8 TPU. When I execute train.py then generates following error

(pid=9454, ip=10.164.0.9) jax runtime initialization starting
2021-07-09 12:11:59,794 ERROR worker.py:78 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::NetworkRunner.run() (pid=9454, ip=10.164.0.9)
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/paramjeetsingh80/mesh-transformer-jax/mesh_transformer/train_actor.py", line 24, in run
TypeError: __new__() missing 1 required positional argument: 'loops'

I am not sure, what this error is? Can someone help be debug this error? Is this error a library versioning issue or something else.

**Comment by richardliaw** [comment]
Can you try using this requirements.txt: https://github.com/kingoflolz/mesh-transformer-jax/blob/09288651e99e7acaee93d7eb03abc5b9cf04ba53/requirements.txt

**Comment by paramjeet2021** [comment]
I am using jax~=0.2.16 in my code as 0.2.12 is not running and it creates a fatal error given in the below two links

https://stackoverflow.com/questions/68306484/not-able-to-import-python-package-jax-in-google-tpu/68308553#68308553

https://stackoverflow.com/posts/68285310/revisions

When I installed 0.2.16 then fatal error goes away and the error in this ticket triggers.

**Comment by richardliaw** [comment]
Can you try changing L24 to:
```
thread_resources.env = ResourceEnv(
    Mesh(np.empty((), dtype=object), ()), 
    ())
```

(add an extra tuple arg to Mesh)?

**Comment by paramjeet2021** [comment]
I tried adding extra empty tuple in mesh as you suggested and it generated the following error.



````lang-python
jax runtime initialization starting
2021-07-10 14:04:06,623 ERROR worker.py:78 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::NetworkRunner.run() (pid=6752, ip=10.164.0.9)
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/paramjeetsingh80/mesh-transformer-jax/mesh_transformer/train_actor.py", line 24, in run
TypeError: __init__() takes 3 positional arguments but 4 were given
````

**Comment by kingoflolz** [comment]
You must use jax==0.2.12 for now, try running https://github.com/kingoflolz/mesh-transformer-jax/blob/master/scripts/init_ray.sh to install the dependencies. If you are tuning on a single TPU device (i.e. v3-8), you should use device_train.py instead of train.py

**Comment by paramjeet2021** [comment]
I am using V3-8 and as per your recommendations, I tried using device_train.py and I can not see the option to pass TPU zone, or TPU name in the argparser function parse_args(). I get the following warning and dies not detect TPU. 

WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "device_train.py", line 178, in <module>
    raise ValueError(msg)
ValueError: each shard needs a separate device, but device count (1) < shard count (8)

**Comment by kingoflolz** [comment]
You must run the code on a TPU VM, and not your local computer or a regular GCE VM

You do not need to download checkpoints if you are training from scratch

**Comment by paramjeet2021** [comment]
I can see the tpu name and zone arguments to be passed into the train.py but I can see them in device_train.py. 

Without passing TPU parameters it is not detecting TPU. How does it detect TPU in the environment?

**Comment by kingoflolz** [comment]
If you are running the code on a TPU VM directly, it will automatically detect the jax devices. See https://cloud.google.com/tpu/docs/jax-quickstart-tpu-vm#display_the_number_of_tpu_cores_available

**Comment by paramjeet2021** [comment]
When I run device_train.py in TPU machine then It presents 3 options and I choose option 3. Any idea, how much time it should take to move forward. My code is stuck at this line for quite some time. 

Eval fn compiled in 21.2282s
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 3
wandb: You chose 'Don't visualize my results'
wandb: W&B syncing is set to `offline` in this directory.  Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.

**Comment by kingoflolz** [comment]
The fine tuning should be running, how long it takes for log messages to print depends on the exact config file settings. Closing as original issue is resolved?

**Comment by paramjeet2021** [comment]
> Can you try changing L24 to:
> 
> ```
> thread_resources.env = ResourceEnv(
>     Mesh(np.empty((), dtype=object), ()), 
>     ())
> ```
> 
> (add an extra tuple arg to Mesh)?

Your solution worked. Thanks.
