### ISSUE TITLE
Memory overflow

### ISSUE THREAD

**Issue by rgzn-aiyun** [kingoflolz/mesh-transformer-jax#44]
Hi, when using 16G T4 to load the model, it causes memory overflow? Is there not enough memory?

**Comment by ahmedjawedaj** [comment]
I also tried slim weights with Tesla T4 and experience the same, It worked well for me with 4 T4

**Comment by kingoflolz** [comment]
See #10 for some solutions, but the model loading using this repository takes approximately 19GB when loading
