### ISSUE TITLE
training problems

### ISSUE THREAD

**Issue by srulikbd** [kingoflolz/mesh-transformer-jax#45]
hey.
I'm trying launching fine tuning the gpt-J model, but  encounter data loading problem-
when running:
```python3 device_train.py --config configs/6B_roto_256.json --tune-model-path 'gs://gpt3-srulik/step_383500```
I get the following error:
`INFO:absl:Starting the local TPU driver.
INFO:absl:Unable to initialize backend 'tpu_driver': Not found: Unable to find driver in registry given worker: local://
INFO:absl:Unable to initialize backend 'gpu': Not found: Could not find registered platform with name: "cuda". Available platform names are: Host TPU Interpreter
jax devices: 8
jax runtime initialized in 3.14744s
`--tune_model_path` passed: we are beginning a fine-tuning run
path to load checkpoint from: gs://gpt3-srulik/step_383500
setting up datasets
Traceback (most recent call last):
  File "device_train.py", line 234, in <module>
    for k, v in params['val_set'].items():
AttributeError: 'str' object has no attribute 'items'
`
I have created a tfrecord using the standard gpt-neo code, uploaded it to my bucket, and changed the config files accordingly.
what could be the problem?

**Comment by kingoflolz** [comment]
Can you post your config file? it looks like the val_set is not set properly

**Comment by srulikbd** [comment]
`{
  "layers": 28,
  "d_model": 4096,
  "n_heads": 16,
  "n_vocab": 50400,
  "norm": "layernorm",
  "pe": "rotary",
  "pe_rotary_dims": 64,

  "seq": 2048,
  "cores_per_replica": 8,
  "per_replica_batch": 1,
  "gradient_accumulation_steps": 16,

  "warmup_steps": 3000,
  "anneal_steps": 300000,
  "lr": 1.2e-4,
  "end_lr": 1.2e-5,
  "weight_decay": 0.1,
  "total_steps": 350000,

  "tpu_size": 256,

  "bucket": "srulik",
  "model_dir": "mesh_jax_pile_6B_rotary",

  "train_set": "BD",
  "val_set": "BD",

  "eval_harness_tasks": [
    "lambada",
    "piqa",
    "hellaswag",
    "winogrande",
    "mathqa",
    "pubmedqa"
  ],

  "val_batches": 100,
  "val_every": 500,
  "ckpt_every": 500,
  "keep_every": 10000,

  "name": "GPT3_6B_pile_rotary",
  "comment": ""
}`

where the BD dataset is a txt file which I converted to tfrecord using gpt-neo standard script..
I put the file in the data folder with the 'BD' name.

**Comment by kingoflolz** [comment]
Follow the format of the config file exactly, you need something similar to:
```
"val_set": {
    "BD": "bd.val.index",
  },
"train_set": {
    "BD": "bd.train.index",
  },
```
See the data directory in the repo for the expected format of the index files
