### ISSUE TITLE
Module 'jax' has no attribute 'process_index'

### ISSUE THREAD

**Issue by IVannarI** [kingoflolz/mesh-transformer-jax#51]
Hi,
I have this problem while running the colab code: 

> module 'jax' has no attribute 'process_index'

I am using the colab code without modifying anything.

This is the screenshot of the error:

![image](https://user-images.githubusercontent.com/82599723/125424726-a3de3fa8-47dd-4252-ae54-826ced54fa5a.png)

Thank you

**Comment by szymonWojdat** [comment]
@IVannarI Apparently 8e88d0c broke this down. You can temporarily resolve the issue by reverting to cfc6312 right after `git clone`:
```!cd mesh-transformer-jax/ && git reset --hard cfc6312d2abab084d2e1e94fc5d91f4cf0926412; cd ..```
at least until a fix is rolled out.

**Comment by kingoflolz** [comment]
oops, fixed in cba2a1bede5b7d0c2ce1fb8f5d0c5b95fd68dc92
