### ISSUE TITLE
Illegal Instruction Core dumped (resharding_example.py)

### ISSUE THREAD

**Issue by Metroman123** [kingoflolz/mesh-transformer-jax#52]
Whenever I try to run resharding_example.py I keep this error here.
`
Illegal instruction (core dumped)`

I made sure to tar the weights and throw them in the root folder of the project and I installed the dependencies needed.
Is there still something that i am missing?

**Comment by kingoflolz** [comment]
That seems like a problem with one of the dependencies. Can you try to track down on which line of code the crach happens?

**Comment by Metroman123** [comment]
It does not seem to have a traceback, I just get the illegal instruction core dumped in terminal. I am rechecking the dependencies as we speak.

**Comment by ahmedjawedaj** [comment]
@Metroman123 There's some issue with your pytorch and its crashing
can you please provide more info like which machine you're using? GPU or TPU? and how you've installed your packages?
I also faced this issue previsouly,  so may be i can help.

**Comment by Metroman123** [comment]
Im running it on gpu. Nvidia rtx 2060 super. Ive done mutliple install with torch but first i tried installing it with cuda11 by copying the installation code from the torch site.

**Comment by ahmedjawedaj** [comment]
try installing tensorflow==2.5.0

**Comment by Metroman123** [comment]
I tried that before, but i'll try it again when i am at my computer.

**Comment by Metroman123** [comment]
Yeah tried it, no difference.

**Comment by kingoflolz** [comment]
Closing as triaged to environment setup. Unfortunately I'm not able to help with these types of issues.
