### ISSUE TITLE
CPU support

### ISSUE THREAD

**Issue by GregoryVPerry** [kingoflolz/mesh-transformer-jax#56]
I'm interested in implementing CPU inference and would be happy to submit a PR for it, if I can figure out xmesh internals for model parallelism. I've taken a look at the resharding example but it looks like that is for a single GPU? Would an 8X or 16X cluster each with 8GB of memory be a viable platform with xmap for distributed inference?

What protocol is xmap using for distributed inference, is it gRPC based?

**Comment by GregoryVPerry** [comment]
For example [#1598](https://github.com/google/jax/issues/1598):
```
import jax
import jax.numpy as jnp

# Global flag to set a specific platform, must be used at startup.
jax.config.update('jax_platform_name', 'cpu')

x = jnp.square(2)
print(repr(x.device_buffer.device()))  # CpuDevice(id=0)
```
Would multiple CpuDevice IDs work within this context? Or will this only support local CPU inference and not distributed CPU?

**Comment by kingoflolz** [comment]
JAX does not support general distributed computation as you are suggesting, only distributed computation within specialized hardware (on a TPU pod). I believe the resharding example should already work on a single large CPU device, assuming you sufficient memory.

**Comment by GregoryVPerry** [comment]
It looks like there is a [JAX MPI](https://github.com/mpi4jax/mpi4jax) implementation that would support clustering via CPU, as well as [multiprocess environment support](https://jax.readthedocs.io/en/latest/multi_process.html)?

**Comment by kingoflolz** [comment]
MPI does not interface with xmap, and multiprocess enviroments are currently only supported on TPUs

**Comment by kingoflolz** [comment]
Closing as I think this would add quite a lot of additional complexity for CPU inference, which is not a goal of this repository
