### ISSUE TITLE
Error in prediction code

### ISSUE THREAD

**Issue by paramjeet2021** [kingoflolz/mesh-transformer-jax#67]
Any update on the issue #65 

Even after following @kingoflolz Recommendations in  the post #65 I am not able to move ahead as library itself breaks and import jax itself abort.

**Comment by hugbubby** [comment]
The instant crash upon importing jax==0.2.12 is also the root concern behind #59 , which was paradoxically closed with the suggestion to make sure jax's version was 0.2.12.

**Comment by kingoflolz** [comment]
To clarify, I'm saying if you cannot install jax==0.2.12 and import it, its an issue with the dependencies, which I have limited time to debug. I believe the root cause in this case is the need to install jaxlib==0.1.67, and init_ray.sh has been updated to reflect this.

**Comment by paramjeet2021** [comment]
@kingoflolz 
You are in action with Jax team over https://github.com/google/jax/issues/6962 and today just 1 hour ago you have submitted a new PR for transformer_shard.py. I just would like to know if the issue is resolved or not yet. Do we have to train a new model or old model will work to use colab_demo.ipynb script?

**Comment by kingoflolz** [comment]
Try installing the dependencies with the updated init_ray.sh, I believe it should work now

**Comment by paramjeet2021** [comment]
https://github.com/kingoflolz/mesh-transformer-jax/blob/master/scripts/init_ray.sh

Above file still use jax 0.2.12, not the new version. I created a new TPU with this configuration and model worked. But it does not work with Jax 0.02.17.

**Comment by kingoflolz** [comment]
yes, the model still does not work with a newer jax version

**Comment by anthonyfuller7** [comment]
> Try installing the dependencies with the updated init_ray.sh, I believe it should work now

I'm a TPU noob, ran init_ray.sh, didn't work (even with jax==0.2.12). Then I checked the jaxlib version and it was 0.1.69. After downgrading to jaxlib==0.1.67 it worked fine. 

Posting this in case it can help another noob :)
