### ISSUE TITLE
how to convert my custom txt data into tfrecords files

### ISSUE THREAD

**Issue by NaveedMaz** [kingoflolz/mesh-transformer-jax#68]
I am trying to finetune it on my custom txt data but i don't know how to convert txt file into tfrecords could you guide me please i am a learner at this point and your help would be very useful for me. thanks!

**Comment by kingoflolz** [comment]
You can use this script (the input expects exactly the same format as gptneo) https://github.com/EleutherAI/gpt-neo/blob/master/data/create_tfrecords.py
