### ISSUE TITLE
Temp 0 doesn't work properly

### ISSUE THREAD

**Issue by summerstay** [kingoflolz/mesh-transformer-jax#69]
Using the online demo, with a prompt of a few words and a temperature of zero tends to give repeated punctuation symbols as a continuation. Nudge it up to temp = .01 and it behaves as GPT-2 and 3 do at zero temperature: usually repetitive, but on a full sentence level. I think the program may not handle inputs of 0 temperature correctly.

**Comment by kingoflolz** [comment]
Yeah, the intended way to do argmax sampling is to use top-p=0 instead
