### ISSUE TITLE
ValueError: cannot reshape array of size 1 into shape (0,8)

### ISSUE THREAD

**Issue by adamfils** [kingoflolz/mesh-transformer-jax#70]
ValueError                                Traceback (most recent call last)
<ipython-input-5-a61c7aa5df54> in <module>
     24 
     25 mesh_shape = (jax.device_count() // cores_per_replica, cores_per_replica)
---> 26 devices = np.array(jax.devices()).reshape(mesh_shape)
     27 
     28 maps.thread_resources.env = maps.ResourceEnv(maps.Mesh(devices, ('dp', 'mp')))

ValueError: cannot reshape array of size 1 into shape (0,8)

**Comment by paramjeet2021** [comment]
It seems it is not detecting TPU.

**Comment by adamfils** [comment]
Yes I am running on my local macbook

**Comment by paramjeet2021** [comment]
This code will not run on local as it requires TPU to execute this.

**Comment by adamfils** [comment]
oh okay Thanks
