### ISSUE TITLE
Batch_inference with `resharding_example.py`

### ISSUE THREAD

**Issue by suzyahyah** [kingoflolz/mesh-transformer-jax#72]
Hi! 

Thanks for this amazing model! **Could you please help to provide batch inference for the `infer` function in `resharding_example.py`?** 

I've tried the following:

infer(["EleutherAI is", "sunny day"]), which gives a single string instead of two strings.

I then tried to modify the function for batches:

```
def infer(context, top_k=40, top_p=0.9, temp=1, gen_len=20):
  tokens = tokenizer.batch_encode_plus(context, padding=True).input_ids
  batched_tokens = np.array(tokens).astype(np.uint32)
  length = np.ones(batched_tokens.shape)
  output = network.generate(batched_tokens, length, gen_len, {"top_p": np.ones(per_replica_batch) * top_p, "top_k": top_k is not None and (np.ones(per_replica_batch, dtype=np.int32) * top_k) or None, "temp": np.ones(per_replica_batch) * temp})

  samples = []
  decoded_tokens = output[1][0]

  for o in decoded_tokens[:, :, 0]:
    samples.append(tokenizer.decode(o))

    print(f"completion done in {time.time() - start:06}s")
    return samples
```

**But got the error in** `jax/experimental/maps.py in _get_axis_sizes(args_flat, in_axes_flat, global_axis_sizes, axis_resource_count):`

`The size of axis batch was previously inferred to be 2, but found an argument of shape (1,) with in_axes specification ['batch', ...]. Shape mismatch occurs in dimension 0: 1 != 2`.  The output of batched_tokens.shape is (2,4) and length.shape is (2,4), so I am not sure what the shape mismatch is referring to. It occurs when the length is shape (1,4) as well. 

Attached screenshot of error below:

![image](https://user-images.githubusercontent.com/2980993/127199800-be3d8faa-12b9-4cb1-a972-ffa9aa1b1a5d.png)

--- 
I am using the params from the `resharding_example.py`:
```
params = {
  "layers": 28,
  "d_model": 4096,
  "n_heads": 16,
  "n_vocab": 50400,
  "norm": "layernorm",
  "pe": "rotary",
  "pe_rotary_dims": 64,
  "early_cast": True,
  "seq": 2048,
  "cores_per_replica": 1,  # only running on one GPU
  "per_replica_batch": 1,
}
```

and I followed the installation from here: ``https://github.com/kingoflolz/mesh-transformer-jax/blob/master/colab_demo.ipynb`` (jax==0.2.1.2)

**Comment by kingoflolz** [comment]
I'm not currently planning to add any new features to the inference functions, but you can look into device_serve.py, which has support for batched inference. I would be happy to accept a PR for this if you do figure it out though.
