### ISSUE TITLE
How to configure greedy sampling?

### ISSUE THREAD

**Issue by theashworld** [kingoflolz/mesh-transformer-jax#73]
Great work folks! From the blog post https://arankomatsuzaki.wordpress.com/2021/06/04/gpt-j/ 

> Completion on a question from BoolQ (SuperGLUE). While both sampling methods result in the same correct conclusion, the nucleus sampling hallucinates and contains incorrect reasoning, while the greedy sampling answers concisely and reasonably. In general, we observed that greedy sampling is more accurate and contains less hallcinations than nucleus sampling when the output is supposed to be short like this, which is predictable given that classification task is usually done with greedy sampling. 

I am using the code from the colab you have published. How do I configure greedy sampling? What should I set `top_p` to? Or is there some other way?

**Comment by kingoflolz** [comment]
top_p = 0 is the intended way method of getting greedy sampling
