### ISSUE TITLE
TPU Requirements

### ISSUE THREAD

**Issue by EternalDusk** [kingoflolz/mesh-transformer-jax#76]
https://github.com/kingoflolz/mesh-transformer-jax/issues/70#issue-953603734

I know that I can't run this locally without a TPU, however, I'm looking at implementing this on a portable device (high-end laptop). Would using an Intel Neural Compute Stick work? 

Item: https://www.amazon.com/Intel-Neural-Compute-Stick-2/dp/B07KT6361R/ref=asc_df_B07KT6361R/?tag=hyprod-20&linkCode=df0&hvadid=320048880417&hvpos=&hvnetw=g&hvrand=18183032492087246699&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9029030&hvtargid=pla-628439506973&psc=1&tag=&ref=&adgrpid=61389685902&hvpone=&hvptwo=&hvadid=320048880417&hvpos=&hvnetw=g&hvrand=18183032492087246699&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9029030&hvtargid=pla-628439506973

If not, are there alternatives or do I _have_ to use Google Collab's TPUs?

**Comment by kingoflolz** [comment]
You can use either a google TPU or a GPU with more than 16GB of VRAM. You could also try running it on a CPU, but the performance will be pretty bad.

**Comment by EternalDusk** [comment]
Sorry to reopen this, but I've followed the instructions from the collab file, yet I still get the error that I referenced. Do you have any instructions to run this locally?

**Comment by EternalDusk** [comment]
How would I be able to run this locally? After looking I haven't found documented settings for setting a TPU, GPU, or CPU.

**Comment by kingoflolz** [comment]
resharding_example.py should run on a CPU or GPU, see the comments for the specifications required
