### ISSUE TITLE
Log generated samples during training

### ISSUE THREAD

**Issue by morganmcg1** [kingoflolz/mesh-transformer-jax#83]
Does anyone have any pointers of how to log generated examples during training? I'm planning on logging them to W&B, so I can check in on what the generation quality is like.

I tried naively just grabbing some of the code from `device_sample.py` and calling it once validation is finished. It generates some sample text, but I get the following error when training resumes:

```
RuntimeError: Resource exhausted: Attempting to reserve 4.44G at the bottom of memory. That was not possible. There are 9.61G free, 0B reserved, and 2.65G reservable.: while running replica 0 and partition 0 of a replicated computation (other replicas may have failed as well)
```

I guess its becuase I'm calling `network.move_xmap` in order to generate, and need to undo that before resuming training? Any pointers how what I need to do?

Full stack trace: https://gist.github.com/morganmcg1/0e4344df49fe3b43243505992ce998d5

Code used for generation:
```
total_batch = per_replica_batch * jax.device_count() // cores_per_replica

context = "EleutherAI is" #input("Type input:")
tokens = tokenizer.encode(context)

provided_ctx = len(tokens)
pad_amount = seq - provided_ctx

padded_tokens = np.pad(tokens, ((pad_amount, 0),)).astype(np.uint32)
batched_tokens = np.array([padded_tokens] * total_batch)
                        
length = np.ones(total_batch, dtype=np.uint32) * len(tokens)
top_p=0.9
temp=0.75
gen_len=512

start = time.time()

### taken from device_sample
local_shards = max(jax.local_device_count() // mesh_shape[1], 1)
# del network.state["opt_state"]
network.state = network.move_xmap(network.state, np.zeros(local_shards))
###

output = network.generate(batched_tokens, length, gen_len, {"top_p": np.ones(total_batch) * top_p, 
                                                                                    "temp": np.ones(total_batch) * temp})
```

**Comment by kingoflolz** [comment]
You shouldn't need that code from device_sample you are calling from the context of device_train. Try just doing the network.generate line?

**Comment by morganmcg1** [comment]
oh you're right, ty, this is going to be great!
