### ISSUE TITLE
Sharding strategy not very clear

### ISSUE THREAD

**Issue by sudhakarsingh27** [kingoflolz/mesh-transformer-jax#84]
On this line, sharding strategy with both ('dp' and 'mp') is used while initializing parameters. 
https://github.com/kingoflolz/mesh-transformer-jax/blob/e2c99b4c420f34f12f09a77a6c11d8acb199ccc3/mesh_transformer/transformer_shard.py#L441

```
{'transformer': FlatMap({
   'transformer_layer_shard_v2/~/layer_norm': FlatMap({'offset': PartitionSpec(None,), 'scale': PartitionSpec(None,)}),
   'transformer_layer_shard_v2/~/linear': FlatMap({
                                            'b': PartitionSpec(None,),
                                            'w': PartitionSpec(None, None, ['mp', 'dp']),
                                          }),
   'transformer_layer_shard_v2/~/linear_1': FlatMap({
                                              'b': PartitionSpec(None,),
                                              'w': PartitionSpec(None, ['mp', 'dp'], None),
                                            }),
 })}
```

But later during training, the sharding strategy is changed dynamically to only 'mp'.
https://github.com/kingoflolz/mesh-transformer-jax/blob/e2c99b4c420f34f12f09a77a6c11d8acb199ccc3/mesh_transformer/transformer_shard.py#L477

```
{'transformer': FlatMap({
   'transformer_layer_shard_v2/~/layer_norm': FlatMap({'offset': PartitionSpec(None,), 'scale': PartitionSpec(None,)}),
   'transformer_layer_shard_v2/~/linear': FlatMap({'b': PartitionSpec(None,), 'w': PartitionSpec(None, None, ['mp'])}),
   'transformer_layer_shard_v2/~/linear_1': FlatMap({'b': PartitionSpec(None,), 'w': PartitionSpec(None, ['mp'], None)}),
 })}
```
Is there a particular reason for doing this?

**Comment by kingoflolz** [comment]
The half precision parameters are only sharded in the model parallel dimension for speed in the forward and backward pass. I've found this technique to be a favorable performance-memory tradeoff for the size of models and TPU pods I'm using.
