### ISSUE TITLE
Finetuning on GPUs

### ISSUE THREAD

**Issue by saichandrapandraju** [kingoflolz/mesh-transformer-jax#85]
Hi,

I could find only TPU finetuning instructions in this repo. Is there a way to finetune this amazing model with GPUs?

**Comment by kingoflolz** [comment]
Its possible, although you should use the pytorch/deepspeed implementation instead of this repository. See a script to do so here: 

https://gist.github.com/kinoc/dca36b12b5e956688a9b92a87ba7c52c

**Comment by widiba03304** [comment]
@kingoflolz Do you mean that it is better to use pytorch/deepspeed implementation instead of this repo bc this repo is optimized for using TPU? or you mean this repo is infeasible to use on GPUs?
