### ISSUE TITLE
Website not connected to model

### ISSUE THREAD

**Issue by Jadiker** [kingoflolz/mesh-transformer-jax#93]
When trying to test prompts on https://6b.eleuther.ai/ it displays "Unable to connect to the model. Please try again."

Is this by chance due to GitHub requiring access tokens rather than command-line access, [starting today](https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/)?

**Comment by cmfox05** [comment]
Sometimes it does say that it's unable to connect to the model, but for me it usually goes away after a few minutes. This time it does seem to be lasting a while though

**Comment by alan-signal** [comment]
Seeing this on the console:
```
Access to fetch at 'https://api.neuro-ai.co.uk/SyncPredict?include_result=true' from origin 'https://6b.eleuther.ai' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by kingoflolz** [comment]
Model is working again now
