### ISSUE TITLE
Change weights file from .tar.zstd to .tar.zst

### ISSUE THREAD

**Issue by ergpopler** [kingoflolz/mesh-transformer-jax#94]
Zstandard uses .zst, not .zstd.

As you can see here: https://engineering.fb.com/2016/08/31/core-data/smaller-and-faster-data-compression-with-zstandard/

The person who created zstandard at facebook is using `.tar.zst`

Wikipedia also states that .zst is the file extension of choice: https://en.wikipedia.org/wiki/Zstandard
and it sites its source.

**Comment by kingoflolz** [comment]
Thanks for letting me know, I'll keep that in mind for future releases. I won't rename the current version of the weights though, as that would introduce compatibility issues.
