### ISSUE TITLE
ImportError: cannot import name 'LayerNormalization' from 'tensorflow.python.keras.layers.normalization' (/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/normalization/__init__.py)

### ISSUE THREAD

**Issue by umajamnon** [kingoflolz/mesh-transformer-jax#97]
I was working on colab demo and this error pop. 

ImportError                               Traceback (most recent call last)
<ipython-input-7-69be91d23870> in <module>()
     21     return samples
     22 
---> 23 print(infer("EleutherAI is")[0])

10 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/__init__.py in <module>()
    144 
    145 # Normalization layers.
--> 146 from tensorflow.python.keras.layers.normalization import LayerNormalization
    147 from tensorflow.python.keras.layers.normalization_v2 import SyncBatchNormalization
    148

**Comment by bubundas17** [comment]
Getting Same issue, On colab

**Comment by artdgn** [comment]
On colab following [this SO advice](https://stackoverflow.com/questions/68080345/importerror-cannot-import-name-layernormalization-from-tensorflow-python-ker) solved this issue for me. So try `!pip install tensorflow==2.3.0`.

**Comment by umajamnon** [comment]
@artdgn  Thanks. It's already working.
