### ISSUE TITLE
Training data format prior to TFRECORD generation

### ISSUE THREAD

**Issue by johncaling40** [kingoflolz/mesh-transformer-jax#99]
Hi, 
Before the TFRECORDS are generated, is it required/benificial to have the data in the LM Data format. The reason why I am asking this is because in all of the sub repositories(ex. github-downloader, stackexchange-dataset for the individual components of the Pile dataset, the data is stored in the LM Data format. I am currently trying to make my own dataset and would like to know. 
Thanks

**Comment by kingoflolz** [comment]
It does not matter, should generate the same tfrecords no matter the input format
